name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-aplication:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21', '1.22']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
